### ISSUE TITLE
Error with WaDE DataType & Uploader: CustomerTypeCV & PopulationServed.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WaDE2.0#91]
Working with UDWRi Site Specific update.  Just discovered the WaDE Data Loader keeps trying to convert both **CustomerTypeCV** & **PopulationServed** from nvarchar to float.  I've tried using dummy values for both, but I'm still getting the same errors.

- **CustomerTypeCV** is suppose to be nvarchar(100), but something in the data loader keeps trying to convert it to a float.
- **PopulationServed** is suppose to be a float, but I can't get the data uploader to recognize it as one, it keeps trying to read it in as a nvarchar.

URL to data files: https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/tree/master/Utah/SiteSpecificAmounts/UDWRi/ProcessedInputData/UDWRisite

**Comment by zlannin** [comment]
I think your issue is bad data in https://github.com/WSWCWaterDataExchange/MappingStatesDataToWaDE2.0/blob/master/Utah/SiteSpecificAmounts/UDWRi/ProcessedInputData/UDWRisite/sitespecificamounts.csv.

If you open that file in Excel and go to row 311 you will see numbers in every column. Could you please fix row 310 and 311 and re-run the data loader.
